### ISSUE TITLE
Bug: Need to fix margin and font-size for mobile width🛠️

### ISSUE THREAD

**Issue by adityamangal1** [mcao/mikecao.me#1]
![IMG_20210801_144521](https://user-images.githubusercontent.com/68494604/127765871-82cf1bcd-6eae-44ba-9b13-771e043155ff.jpg)

![IMG_20210801_144447](https://user-images.githubusercontent.com/68494604/127765872-ef5b7e06-2f84-4ea8-8de5-033331da13c7.jpg)

Would love to fix that

**Comment by mcao** [comment]
Issue noted! Would love a PR on this.

**Comment by adityamangal1** [comment]
> Issue noted! Would love a PR on this.

Sure ✨
